### ISSUE TITLE
[Bug] Model configuration and unicity tests

### ISSUE THREAD

**Issue by raphaelvarieras** [fivetran/dbt_zuora#9]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

The following tests are failing:
- test.zuora.unique_zuora__subscription_overview_subscription_key
- test.zuora.unique_zuora__line_item_history_invoice_item_id

For subscriptions, the issue is that there may be multiple amendments for a given subscription ID, therefore the join of subscriptions on amendments generates multiple records.

For line item history, it appears to be an issue stemming from the use of taxation items. I have the option enabled and this is where the duplicates are coming from for me:
<img width="610" alt="image" src="https://github.com/fivetran/dbt_zuora/assets/6558178/5f98441c-d77e-4fe9-8852-ea9fd41ba8f5">

### Relevant error log or model output

```shell
01:32:17 Writing runtime sql for node "test.zuora.unique_zuora__line_item_history_invoice_item_id.006d565076"
01:32:17 Using snowflake connection "test.zuora.unique_zuora__line_item_history_invoice_item_id.006d565076"
01:32:17 On test.zuora.unique_zuora__line_item_history_invoice_item_id.006d565076: select
      count(*) as failures,
      count(*) != 0 as should_warn,
      count(*) != 0 as should_error
    from (
      
    
    

select
    invoice_item_id as unique_field,
    count(*) as n_records

from DBT.raphael_zuora.zuora__line_item_history
where invoice_item_id is not null
group by invoice_item_id
having count(*) > 1



      
    ) dbt_internal_test
01:32:17 Opening a new connection, currently in state closed
01:32:18 SQL status: SUCCESS 1 in 2.0 seconds
01:32:18 Timing info for test.zuora.unique_zuora__line_item_history_invoice_item_id.006d565076 (execute): 01:32:17.112777 => 01:32:18.756402
01:32:18 On test.zuora.unique_zuora__line_item_history_invoice_item_id.006d565076: Close
01:32:18 1803 of 1810 FAIL 12723 unique_zuora__line_item_history_invoice_item_id ........ [FAIL 12723 in 1.71s]
01:32:18 Finished running node test.zuora.unique_zuora__line_item_history_invoice_item_id.006d565076
```

### Expected behavior

N/A

### dbt Project configurations

n/A

### Package versions

0.2.0

### What database are you using dbt with?

snowflake

### dbt Version

1.6

### Are you willing to open a PR to help address this issue?

- [ ] Yes.
- [ ] Yes, but I will need assistance and will schedule time during our [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance
- [X] No.

**Comment by fivetran-avinash** [comment]
Hi @raphaelvarieras , thanks for investigating. I was able to reproduce test errors for each case. 

I would love your input as you are probably more familiar with Zuora than me!

For `test.zuora.unique_zuora__subscription_overview_subscription_key`, I think you are right that we did not account for a subscription having multiple amendments. My proposed solution would be to adjust the surrogate key to include amendment id to ensure uniqueness.  

For `test.zuora.unique_zuora__line_item_history_invoice_item_id`, I was also able to reproduce. It looks like we did not account for the same invoice item being tied to multiple taxation items, causing duplicates. We obviously don't want multiple invoice items in this end model!  

If we wanted to pull this field in to support customers with multicurrency, my thoughts are the best approach would be to do a sum of all the `taxation_home_currency` rows associated with an invoice item [in this CTE](https://github.com/fivetran/dbt_zuora/blob/main/models/zuora__line_item_history.sql#L67-L76) rather than pulling the most recent record, then joining that in. That should fix the duplicate issue. 

What are your thoughts here? I believe these are the best paths forward, but you probably have more expertise with these models than me. 

(Also, if these solutions make sense, since they would be relatively quick fixes, would you be interested in contributing a PR to fix these? We can definitely take on these in a future sprint but if you had time to take them on it would expedite release!)

**Comment by raphaelvarieras** [comment]
Hi @fivetran-avinash - I think your suggestions are great, that's what I was thinking as well!

Re: contribution. I'm happy to maybe review a PR but I don't have a whole lot of time to actually tweak the models myself at the moment.

**Comment by fivetran-avinash** [comment]
No worries @raphaelvarieras ! These are relatively quick fixes, so we will work on these in a coming sprint and keep you updated on future development. When we have a branch/PR ready, I'll contact you to ratify our approach works.

Let me know if you have any other questions!

**Comment by fivetran-catfritz** [comment]
Hi @raphaelvarieras thank you again for opening this issue. I have created a test branch that you can install and should address this issue and also https://github.com/fivetran/dbt_zuora_source/issues/10. If you would like to try it out, you can use the below snippet to install the test branch. 

```yml
  - git: https://github.com/fivetran/dbt_zuora.git
    revision: bug/unique-tests
    warn-unpinned: false
```

If you're able to try this out, please let me know how it works for you!
